✅ Add tests
jiacai2050/promql-prettier pull request #4
Opened 2022-08-27 03:36 UTC by vegerot

- Added tests from README
- Refactor a bit of the code to make it more easily testable

2022-08-27 03:44 UTC, vegerot commented
It sounds like I should add a test for UTF-8 compatibility

2022-08-27 12:30 UTC, jiacai2050 requested changes

2022-08-27 12:30 UTC, jiacai2050 commented on util.go
> +func FormatString(s string) string {
- How about name this function `Prettier`

2022-08-27 12:30 UTC, jiacai2050 commented on util.go
> +		panic(err)
it should return err out

2022-08-27 12:30 UTC, jiacai2050 commented on main_test.go
> +package main_test
I think we can just put this file in `main` package

2022-08-27 12:30 UTC, jiacai2050 commented on main_test.go
> +	type gotWant struct {
```
tests := []struct {
input string
expected string
}{
  {},
  {},
..
}
```

2022-08-29 21:35 UTC, vegerot commented on util.go
> +func FormatString(s string) string {
Good idea

2022-08-29 21:38 UTC, vegerot commented on util.go
> +		panic(err)
thanks

2022-08-29 21:39 UTC, vegerot commented on main_test.go
> +	type gotWant struct {
I like that!

2022-08-29 21:39 UTC, vegerot commented on main_test.go
> +package main_test
I prefer putting my tests in a different package to make sure I'm only testing exported fields

For `main` it doesn't really matter either way, but I think this is more idiomatic

2022-08-29 21:43 UTC, vegerot commented on main_test.go
> +package main_test
See https://pkg.go.dev/testing and https://github.com/golang/go/issues/25223#issuecomment-1201120914

2022-08-29 21:44 UTC, vegerot commented on main_test.go
> +package main_test
If you feel strongly about the package naming I will change it

2022-08-30 00:22 UTC, jiacai2050 commented on main_test.go
> +package main_test
Good point

2022-08-30 00:23 UTC, jiacai2050 approved these changes
Thanks

2022-08-30 00:24 UTC, merged